#!perl

my %hash;

for @*ARGS -> $command {
	unless $command.IO.e {
		say "Command [$command] does not exist!";
		next;
		};
	unless $command.IO.x {
		say "Command [$command] is not executable!";
		next;
		};

	say "===== $command";

	for 2, 4 ... 18 -> $n {
		my $start  = now;
		my $output = qq:x{ $command $n };
		my $end    = now;

		my $elapsed = $end - $start;

		%hash{$command}{$n} = $elapsed;
		say "$n: $elapsed";
		}
	}

say %hash.perl;
